from enum import Enum
from pydantic import BaseModel, Field


class SubtaskStatus(str, Enum):
    """Status of a subtask execution."""

    OK = "OK"
    FAILED = "FAILED"


class TaskRequest(BaseModel):
    """Request to process a main task.

    @param description: Full description of the task to be performed.
    """

    description: str


class Subtask(BaseModel):
    """A single subtask decomposed from a main task.

    @param id: Unique identifier for the subtask.
    @param kind: The type or category of the subtask.
    @param description: What needs to be done.
    @param dependencies: List of subtask IDs that must complete before this one.
    """

    id: str
    kind: str = "generic"
    description: str
    dependencies: list[str] = Field(default_factory=list)


class SubtaskResult(BaseModel):
    """Result of a subtask execution.

    @param subtask_id: ID of the executed subtask.
    @param agent_id: Identifier of the agent that executed the subtask.
    @param status: Final execution status (OK or FAILED).
    @param content: The output content generated by the agent.
    @param error: Optional error message if the subtask failed.
    """

    subtask_id: str
    agent_id: str
    status: SubtaskStatus
    content: str
    error: str | None = None


class SwarmResult(BaseModel):
    """Final aggregated result of the entire swarm execution.

    @param task_id: Unique identifier of the original task.
    @param results: List of individual subtask results.
    @param final_content: Aggregated final output.
    """

    task_id: str
    results: list[SubtaskResult] = Field(default_factory=list)
    final_content: str
